version: '3.8'

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - localhost
    ports:
      - "8000:8000"
    depends_on:
      postgres_db:
        condition: service_healthy
      redis_db:
        condition: service_healthy
  postgres_db:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_DB=vkbot_kts
      - POSTGRES_USER=vkbot
      - POSTGRES_PASSWORD=vkbot
    networks:
      - localhost
    expose:
      - 5432
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vkbot"]
      interval: 5s
      timeout: 30s
      retries: 100
  redis_db:
    container_name: redis_db
    image: redis:6.2.6-alpine
    networks:
      - localhost
    expose:
      - 6379
    ports:
      - "9000:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 30s
      retries: 100
networks:
  localhost:
